BinTree.h
BinNodePosi
Referenced by BinNode< T >::travLevel.
stature
Referenced by BinTree< T >::updateHeight.
IsRoot
IsLChild
IsRChild
HasParent
HasLChild
Referenced by travIn_I3, travIn_I4, BinNode< T >::travLevel, travPre_I1.
HasRChild
Referenced by travIn_I3, travIn_I4, BinNode< T >::travLevel, travPre_I1.
HasChild
HasBothChild
IsLeaf
sibling
uncle
FromParentTo
Referenced by BinTree< T >::remove, BinTree< T >::secede.
RBColor
void release(T x)
References Cleaner< T >::clean.
Referenced by removeAt.
void travPre_I1(BinNodePosi(T) x, VST &visit)
References Vector< T >::empty, HasLChild, HasRChild, Stack< T >::pop, Stack< T >::push.
Referenced by BinNode< T >::travPre.
static void visitAlongVine(BinNodePosi(T) x, VST &visit, Stack< BinNodePosi(T)> &S)
Referenced by travPre_I2.
void travPre_I2(BinNodePosi(T) x, VST &visit)
References Vector< T >::empty, Stack< T >::pop, visitAlongVine.
Referenced by BinNode< T >::travPre.
void travPre_R(BinNodePosi(T) x, VST &visit)
Referenced by BinNode< T >::travPre.
static void goAlongVine(BinNodePosi(T) x, Stack< BinNodePosi(T)> &S)
Referenced by travIn_I1.
void travIn_I1(BinNodePosi(T) x, VST &visit)
References Vector< T >::empty, goAlongVine, Stack< T >::pop.
Referenced by BinNode< T >::travIn.
void travIn_I2(BinNodePosi(T) x, VST &visit)
References Vector< T >::empty, Stack< T >::pop, Stack< T >::push.
Referenced by BinNode< T >::travIn.
void travIn_I3(BinNodePosi(T) x, VST &visit)
References HasLChild, HasRChild.
Referenced by BinNode< T >::travIn.
void travIn_I4(BinNodePosi(T) x, VST &visit)
References HasLChild, HasRChild.
Referenced by BinNode< T >::travIn.
void travIn_R(BinNodePosi(T) x, VST &visit)
Referenced by BinNode< T >::travIn.
static int removeAt(BinNodePosi(T) x)
References n, release.
Referenced by BinTree< T >::remove.