List
int List< T >::_size
int List< T >::n
T const & List< T >::e
List< T >::ListNodePosi(T) header
List< T >::ListNodePosi(T) trailer
void List< T >::init()
int List< T >::clear()
void List< T >::copyNodes(ListNodePosi(T) p, int n)
void List< T >::merge(ListNodePosi(T)&pp, int n, List< T > &L, ListNodePosi(T) q, int m)
References ListNode< T >::ListNodePosi, p, List< T >::remove.
void List< T >::mergeSort(ListNodePosi(T)&p, int n)
References ListNode< T >::ListNodePosi, p.
void List< T >::selectionSort(ListNodePosi(T) p, int n)
References ListNode< T >::ListNodePosi, n, p, while.
void List< T >::insertionSort(ListNodePosi(T) p, int n)
References n.
List< T >::List()
List< T >::List(List< T > const &L)
References List< T >::size.
List< T >::List(List< T > const &L, Rank r, int n)
References ListNode< T >::ListNodePosi, p.
List< T >::List(ListNodePosi(T) p, int n)
List< T >::~List()
Rank List< T >::size() const
Referenced by List< T >::List.
bool List< T >::empty() const
Referenced by BinNode< T >::travLevel.
T & List< T >::operator[](Rank r) const
References ListNode< T >::ListNodePosi, p.
List< T >::ListNodePosi(T) first() const
List< T >::ListNodePosi(T) last() const
bool List< T >::valid(ListNodePosi(T) p)
References p.
int List< T >::disordered() const
References ListNode< T >::ListNodePosi, n.
List< T >::ListNodePosi(T) find(T const &e) const
List< T >::ListNodePosi(T) find(T const &e
int List< T >::ListNodePosi(T) p) const
List< T >::ListNodePosi(T) search(T const &e) const
List< T >::ListNodePosi(T) search(T const &e
int List< T >::ListNodePosi(T) p) const
List< T >::ListNodePosi(T) selectMax(ListNodePosi(T) p
List< T >::ListNodePosi(T) selectMax()
List< T >::ListNodePosi(T) insertAsFirst(T const &e)
List< T >::ListNodePosi(T) insertAsLast(T const &e)
List< T >::ListNodePosi(T) insertA(ListNodePosi(T) p
List< T >::ListNodePosi(T) insertB(ListNodePosi(T) p
T List< T >::remove(ListNodePosi(T) p)
References p.
Referenced by List< T >::merge.
void List< T >::merge(List< T > &L)
void List< T >::sort(ListNodePosi(T) p, int n)
void List< T >::sort()
int List< T >::deduplicate()
References ListNode< T >::ListNodePosi.
int List< T >::uniquify()
References ListNode< T >::ListNodePosi.
void List< T >::reverse()
References ListNode< T >::ListNodePosi, p.
void List< T >::traverse(void(*visit)(T &))
References ListNode< T >::ListNodePosi.
void List< T >::traverse(VST &visit)
References ListNode< T >::ListNodePosi.