Stack
void Stack< T >::push(T const &e)
References Vector< T >::insert, Vector< T >::size.
Referenced by travIn_I2, travPre_I1.
T Stack< T >::pop()
References Vector< T >::size.
Referenced by travIn_I1, travIn_I2, travPre_I1, travPre_I2.
T& Stack< T >::top()
References Vector< T >::size.