Fib
Rank Fib::f
Rank Fib::g
Fib::Fib(Rank n)
Rank Fib::get()
Referenced by fibSearch, simpleFibSearch.
Rank Fib::next()
Rank Fib::prev()
Referenced by fibSearch, simpleFibSearch.