ListNode
T ListNode< T >::data
ListNode< T >::ListNodePosi(T) pred
Referenced by List< T >::deduplicate, List< T >::disordered, List< T >::List, List< T >::merge, List< T >::mergeSort, List< T >::operator[], List< T >::reverse, List< T >::selectionSort, List< T >::traverse, List< T >::uniquify.
ListNode< T >::ListNodePosi(T) succ
ListNode< T >::ListNode()
ListNode< T >::ListNode(T e, ListNodePosi(T) p=nullptr, ListNodePosi(T) s=nullptr)
ListNode< T >::ListNodePosi(T) insertAsPred(T const &e)
ListNode< T >::ListNodePosi(T) insertAsSucc(T const &e)